### ISSUE TITLE
Coverage generation broken

### ISSUE THREAD

**Issue by mmikulicic** [cesanta/fossa#201]
Regression introduced in d6d20f63569c8ea0d9

```
CLEAN   coverage
CLEAN   all
CC      unit_test_gcov
In file included from ../modules/iobuf.c:22:
../modules/internal.h:34:59: error: declaration of 'union socket_address' will not be visible outside of this function [-Werror,-Wvisibility]
                                                    union socket_address *sa,
                                                          ^
../modules/internal.h:35:60: error: declaration of 'struct ns_add_sock_opts' will not be visible outside of this function [-Werror,-Wvisibility]
                                                    struct ns_add_sock_opts);
                                                           ^
../modules/internal.h:37:57: error: declaration of 'union socket_address' will not be visible outside of this function [-Werror,-Wvisibility]
NS_INTERNAL int ns_parse_address(const char *str, union socket_address *sa,
                                                        ^
3 errors generated.
In file included from ../modules/net.c:29:
../modules/internal.h:34:59: error: declaration of 'union socket_address' will not be visible outside of this function [-Werror,-Wvisibility]
                                                    union socket_address *sa,
                                                          ^
../modules/internal.h:35:60: error: declaration of 'struct ns_add_sock_opts' will not be visible outside of this function [-Werror,-Wvisibility]
                                                    struct ns_add_sock_opts);
                                                           ^
../modules/internal.h:37:57: error: declaration of 'union socket_address' will not be visible outside of this function [-Werror,-Wvisibility]
NS_INTERNAL int ns_parse_address(const char *str, union socket_address *sa,
```

**Comment by mmikulicic** [comment]
fixed
